# Generated by Django 6.0.2 on 2026-03-02 19:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizada', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('km_atual', models.PositiveIntegerField(verbose_name='Quilometragem Atual')),
                ('nivel_combustivel', models.CharField(choices=[('Reserva', 'Reserva'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('Cheio', 'Cheio')], default='Cheio', max_length=10)),
                ('farol', models.BooleanField(default=False, verbose_name='Faróis (Baixo/Alto)')),
                ('lanterna', models.BooleanField(default=False, verbose_name='Lanterna')),
                ('re_freio', models.BooleanField(default=False, verbose_name='Iluminação de Ré/Freio')),
                ('piscas', models.BooleanField(default=False, verbose_name='Condição dos Piscas')),
                ('pneus', models.BooleanField(default=False, verbose_name='Condição dos Pneus')),
                ('amortecedor', models.BooleanField(default=False, verbose_name='Amortecedores')),
                ('bateria', models.BooleanField(default=False, verbose_name='Bateria')),
                ('oleo', models.BooleanField(default=False, verbose_name='Nível do Óleo')),
                ('arrefecimento_radiador', models.BooleanField(default=False, verbose_name='Arrefecimento')),
                ('vazamentos', models.BooleanField(default=False, verbose_name='Sem vazamentos?')),
                ('limpadores', models.BooleanField(default=False, verbose_name='Limpadores de Vidro')),
                ('vidros', models.BooleanField(default=False, verbose_name='Vidros')),
                ('retrovisor', models.BooleanField(default=False, verbose_name='Retrovisores')),
                ('estepe', models.BooleanField(default=False, verbose_name='Estepe')),
                ('macaco', models.BooleanField(default=False, verbose_name='Macaco')),
                ('chave_roda', models.BooleanField(default=False, verbose_name='Chave de Roda')),
                ('trava_porta', models.BooleanField(default=False, verbose_name='Trava Porta')),
                ('trava_porta_mala', models.BooleanField(default=False, verbose_name='Trava Porta Mala')),
                ('trava_capo', models.BooleanField(default=False, verbose_name='Trava Capô')),
                ('porta_luva', models.BooleanField(default=False, verbose_name='Porta Luvas')),
                ('lataria', models.BooleanField(default=False, verbose_name='Lataria (Sem avarias)')),
                ('buzina', models.BooleanField(default=False, verbose_name='Buzina')),
                ('iluminacao_interna', models.BooleanField(default=False, verbose_name='Luz Interna')),
                ('bancos', models.BooleanField(default=False, verbose_name='Bancos')),
                ('tapetes', models.BooleanField(default=False, verbose_name='Tapetes')),
                ('freio_mao', models.BooleanField(default=False, verbose_name='Freio de Mão')),
                ('ar_condicionado', models.BooleanField(default=False, verbose_name='Ar Condicionado')),
                ('som', models.BooleanField(default=False, verbose_name='Som')),
                ('teto', models.BooleanField(default=False, verbose_name='Teto')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Detalhadas')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('renavam', models.CharField(max_length=11, unique=True)),
                ('documento_impresso', models.FileField(upload_to='veiculos/docs/')),
                ('fipe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('foto', models.ImageField(upload_to='veiculos/fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_patrao', models.BooleanField(default=False, verbose_name='É Gestor/Admin')),
                ('is_motorista', models.BooleanField(default=False, verbose_name='É Motorista/Funcionário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FotoAvaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Risco na porta lateral esquerda', max_length=255)),
                ('imagem', models.ImageField(upload_to='checklists/avarias/%Y/%m/%d/')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_avarias', to='frota.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('numero_cnh', models.CharField(max_length=20, verbose_name='Número CNH')),
                ('validade_cnh', models.DateField(verbose_name='Validade da CNH')),
                ('cnh_impressa', models.FileField(upload_to='funcionarios/cnh/', verbose_name='CNH Digital/Scanner')),
                ('cargo', models.CharField(default='Motorista', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.funcionario'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.veiculo'),
        ),
    ]
