# Generated by Django 6.0.2 on 2026-03-02 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_funcionario_cadastrado_por_funcionario_nome_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='porta_luva',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='trava_capo',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='trava_porta',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='trava_porta_mala',
        ),
        migrations.AddField(
            model_name='checklist',
            name='nome_checklist',
            field=models.CharField(max_length=100, null=True, verbose_name='Título do Checklist'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='amortecedor',
            field=models.BooleanField(default=False, verbose_name='Amortecedor OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='ar_condicionado',
            field=models.BooleanField(default=False, verbose_name='Ar Condicionado OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='arrefecimento_radiador',
            field=models.BooleanField(default=False, verbose_name='Arrefecimento OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='bancos',
            field=models.BooleanField(default=False, verbose_name='Bancos OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='bateria',
            field=models.BooleanField(default=False, verbose_name='Bateria OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='buzina',
            field=models.BooleanField(default=False, verbose_name='Buzina OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='chave_roda',
            field=models.BooleanField(default=False, verbose_name='Chave de Roda OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='estepe',
            field=models.BooleanField(default=False, verbose_name='Estepe OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='farol',
            field=models.BooleanField(default=False, verbose_name='Faróis OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='freio_mao',
            field=models.BooleanField(default=False, verbose_name='Freio de Mão OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='iluminacao_interna',
            field=models.BooleanField(default=False, verbose_name='Luz Interna OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='km_atual',
            field=models.PositiveIntegerField(verbose_name='KM Atual'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='lanterna',
            field=models.BooleanField(default=False, verbose_name='Lanterna OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='lataria',
            field=models.BooleanField(default=False, verbose_name='Lataria OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='limpadores',
            field=models.BooleanField(default=False, verbose_name='Limpadores OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='macaco',
            field=models.BooleanField(default=False, verbose_name='Macaco OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frota.funcionario'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='oleo',
            field=models.BooleanField(default=False, verbose_name='Óleo OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='piscas',
            field=models.BooleanField(default=False, verbose_name='Piscas OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='pneus',
            field=models.BooleanField(default=False, verbose_name='Pneus OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='re_freio',
            field=models.BooleanField(default=False, verbose_name='Ré/Freio OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='retrovisor',
            field=models.BooleanField(default=False, verbose_name='Retrovisores OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='som',
            field=models.BooleanField(default=False, verbose_name='Som OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='tapetes',
            field=models.BooleanField(default=False, verbose_name='Tapetes OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='teto',
            field=models.BooleanField(default=False, verbose_name='Teto OK?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='vazamentos',
            field=models.BooleanField(default=False, verbose_name='Livre de Vazamentos?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='vidros',
            field=models.BooleanField(default=False, verbose_name='Vidros OK?'),
        ),
        migrations.AlterField(
            model_name='fotoavaria',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição da Avaria'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Gestor Responsável'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='fipe',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor FIPE'),
        ),
    ]
