# Generated by Django 6.0.2 on 2026-03-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0004_alter_funcionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('Motorista', 'Motorista'), ('Gestor', 'Gestor')], default='Motorista', max_length=100),
        ),
    ]
