# Generated by Django 6.0.2 on 2026-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0005_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cnh_impressa',
            field=models.FileField(blank=True, null=True, upload_to='funcionarios/cnh/', verbose_name='CNH Digital/Scanner'),
        ),
    ]
