# Generated by Django 6.0.2 on 2026-03-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0007_checklist_atualizado_em_checklist_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='criado_em',
        ),
    ]
