# Generated by Django 6.0.2 on 2026-03-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0008_remove_checklist_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='atualizado_em',
        ),
    ]
