# Generated by Django 6.0.2 on 2026-03-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0009_remove_checklist_atualizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.IntegerField(max_length=11, unique=True),
        ),
    ]
