# Generated by Django 6.0.2 on 2026-03-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0010_alter_veiculo_ano_alter_veiculo_renavam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
