# Generated by Django 6.0.2 on 2026-03-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0011_alter_veiculo_placa_alter_veiculo_renavam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='fipe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Valor FIPE'),
        ),
    ]
