# Generated by Django 6.0.2 on 2026-03-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0012_alter_veiculo_fipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
