# Generated by Django 6.0.2 on 2026-03-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0013_veiculo_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoavaria',
            options={'verbose_name': 'Foto de Avaria', 'verbose_name_plural': 'Fotos de Avarias'},
        ),
        migrations.AlterField(
            model_name='fotoavaria',
            name='imagem',
            field=models.ImageField(upload_to='checklists/avarias/%Y/%m/%m/'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
