# Generated by Django 6.0.2 on 2026-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0014_alter_fotoavaria_options_alter_fotoavaria_imagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Veículo'},
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='documento_impresso',
            field=models.FileField(blank=True, null=True, upload_to='veiculos/docs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/fotos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(db_index=True, max_length=7, unique=True),
        ),
    ]
