# Generated by Django 6.0.2 on 2026-03-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0015_alter_veiculo_options_alter_funcionario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='carga',
            field=models.BooleanField(default=False, verbose_name='Carga Ok?'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tacografo',
            field=models.BooleanField(default=False, verbose_name='Tacógrafo Ok?'),
        ),
    ]
