# Generated by Django 6.0.2 on 2026-04-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0016_checklist_carga_checklist_tacografo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
