# Generated by Django 6.0.2 on 2026-04-30 22:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0017_fix_veiculo_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='tipo',
            field=models.CharField(choices=[('pre_viagem', 'Pré-Viagem'), ('pos_viagem', 'Pós-Viagem'), ('geral', 'Geral')], default='geral', max_length=20, verbose_name='Tipo de Inspeção'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado para Despacho'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='km_proxima_revisao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM da Próxima Revisão'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='motivo_bloqueio',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Bloqueio'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='vencimento_crlv',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento CRLV'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='vencimento_seguro',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento Seguro'),
        ),
        migrations.AlterField(
            model_name='fotoavaria',
            name='imagem',
            field=models.ImageField(upload_to='checklists/avarias/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('km_atual', models.PositiveIntegerField(verbose_name='KM no Abastecimento')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Litros Abastecidos')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('tipo_combustivel', models.CharField(choices=[('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('gnv', 'GNV'), ('flex', 'Flex')], default='diesel', max_length=20, verbose_name='Tipo de Combustível')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='frota.funcionario')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos_registrados', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='frota.veiculo')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaAvaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Itens com Falha')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Reparo'), ('em_reparo', 'Em Reparo'), ('resolvida', 'Resolvida')], default='aguardando', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('nota_resolucao', models.TextField(blank=True, null=True, verbose_name='Nota de Resolução')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='frota.checklist')),
                ('resolvida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_resolvidas', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='frota.veiculo')),
            ],
            options={
                'verbose_name': 'Ocorrência de Avaria',
                'verbose_name_plural': 'Ocorrências de Avarias',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='OrdemManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do Serviço')),
                ('responsavel', models.CharField(blank=True, max_length=200, verbose_name='Responsável / Oficina')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('data_agendada', models.DateField(blank=True, null=True, verbose_name='Data Agendada')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo (R$)')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL)),
                ('ocorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='frota.ocorrenciaavaria', verbose_name='Ocorrência vinculada')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_manutencao', to='frota.veiculo')),
            ],
            options={
                'verbose_name': 'Ordem de Manutenção',
                'verbose_name_plural': 'Ordens de Manutenção',
                'ordering': ['-criada_em'],
            },
        ),
    ]
