# Generated by Django 6.0.2 on 2026-05-08 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0018_add_ocorrencia_manutencao_abastecimento_veiculo_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='data_realizada',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='nivel_combustivel',
            field=models.CharField(choices=[('Reserva', 'Reserva'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('Cheio', 'Cheio')], db_index=True, default='Cheio', max_length=10),
        ),
        migrations.AlterField(
            model_name='ocorrenciaavaria',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Reparo'), ('em_reparo', 'Em Reparo'), ('resolvida', 'Resolvida')], db_index=True, default='aguardando', max_length=20),
        ),
    ]
