# Generated by Django 6.0.2 on 2026-08-13 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0019_add_db_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cnh_impressa',
            field=models.FileField(blank=True, null=True, upload_to='funcionarios/cnh/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='CNH Digital/Scanner'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='documento_impresso',
            field=models.FileField(blank=True, null=True, upload_to='veiculos/docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
