# Generated by Django 6.0.2 on 2026-08-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0020_alter_funcionario_cnh_impressa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='validade_cnh',
            field=models.DateField(db_index=True, verbose_name='Validade da CNH'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='vencimento_crlv',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Vencimento CRLV'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='vencimento_seguro',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Vencimento Seguro'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciaavaria',
            index=models.Index(fields=['veiculo', 'status'], name='frota_ocorr_veiculo_7c0aa4_idx'),
        ),
    ]
