# Generated by Django 6.0.2 on 2026-08-13 22:10

from django.db import migrations, models


def preencher_nome_checklist_vazio(apps, schema_editor):
    """Backfill de segurança: preenche nome_checklist para qualquer
    registro que porventura esteja NULL, antes do campo virar NOT NULL.
    No ambiente de desenvolvimento não há nenhum registro assim, mas o
    banco de produção não foi conferido — evita quebrar a migration lá."""
    Checklist = apps.get_model('frota', 'Checklist')
    Checklist.objects.filter(nome_checklist__isnull=True).update(
        nome_checklist='Checklist sem título'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0021_alter_funcionario_validade_cnh_alter_veiculo_ativo_and_more'),
    ]

    operations = [
        migrations.RunPython(preencher_nome_checklist_vazio, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='checklist',
            name='nome_checklist',
            field=models.CharField(max_length=100, verbose_name='Título do Checklist'),
        ),
    ]
