# Generated by Django 6.0.2 on 2026-08-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0022_alter_checklist_nome_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='tablet_cigame',
            field=models.BooleanField(default=False, verbose_name='Tablet Entregas CIGAME Ok?'),
        ),
    ]
