# Generated by Django 6.0.2 on 2026-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0023_checklist_tablet_cigame'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='bloqueio_automatico',
            field=models.BooleanField(default=False, verbose_name='Bloqueio Automático (Avaria Crítica)'),
        ),
    ]
